### ISSUE TITLE
Solid Icons fill color hardcoded

### ISSUE THREAD

**Issue by xerxes333** [gcw07/vue-tailwind-icons#2]
why are solid icons path attributes fill hardcoded as hex values rather than using currentColor? I am unable to change the color of the solid icons with tailwind classes.

**Comment by gcw07** [comment]
Looking into it. Might have copied the wrong icon folder.

**Comment by gcw07** [comment]
I just published a new version. I used the optimized version of the icon sets instead of the source ones. See if that fixes it.

**Comment by xerxes333** [comment]
Perfect, that appears to have resolved the issue thanks for looking into that so quickly!

**Comment by gcw07** [comment]
No problem. Thanks for reporting it. Glad that fixed it. I don't personally use the solid icons much, just the outline ones, so never even noticed.
